version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.17
    ports:
      - "10000:3306"
    expose:
      - "10000"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dockeruser
      - MYSQL_PASSWORD=dockeruser
      - MYSQL_DATABASE=ecom
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 3
      # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 5s
    #   retries: 10
    # volumes:
    #   - ecom-datavolume:/var/lib/ecom

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 5001:80
    depends_on:
      - mysqldb

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    expose:
      - '3000'
    stdin_open: true
    depends_on:
      - backend

# volumes:
#   ecom-datavolume: